# Generated by Django 4.2.7 on 2024-01-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
